# conda activate pytorch
# cd HA-SLR-GCN/Code/Skeleton/Network/SL_GCN/
# python main_base.py --config config/sign_cvpr_A_hands/AUTSL/train_joint_autsl.yaml  > log/joint_autsl.`date +%Y%m%d%H%M`.log

########################## Train ##########################
phase: train

# #optim
train_base_lr: 0.1
step: [150, 200]

########################## MODEL  ##########################

# HA-SLR-GCN 
Experiment_name: AUTSL/Joint/autsl_joint_27_cvpr_hand_aware_sl_lgcn_baseline   
model: model.hand_aware_sl_lgcn.Model

############ Hyperparameter ############

device: [1]

# es: True
es_patience: 50
es: False
num_epoch: 500
# eval_pkl: xxxx

warm_up_epoch: 20

########################## Arguments  ##########################

# feeder
feeder: feeders.feeder_cvpr.Feeder
train_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/train_data_joint.npy
  label_path: ./data/sign_autsl/27_cvpr/train_label.pkl
  debug: False   # If true, only use the first 100 samples  
  window_size: 100 
  random_choose: True   # 在debug的基础上，随机选择视频起始帧、输出长度为window_size的帧序列  TemporalRandomCrop
  random_shift: True  # 随机偏移，偏移片段用0填充   # 在序列头部 填充全0帧
  normalization: True
  random_mirror: True   # 随机镜像，增加 多样性   # 当前帧 是否翻转
  random_mirror_p: 0.5   # 随机镜像的阈值
  is_vector: False  # 相关：random_shift、normalization、random_mirror

val_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/val_data_joint.npy    
  label_path: ./data/sign_autsl/27_cvpr/val_label.pkl
  random_mirror: False
  normalization: True
  debug: False

test_feeder_args:
  data_path: ./data/sign_autsl/27_cvpr/test_data_joint.npy
  label_path: ./data/sign_autsl/27_cvpr/test_label.pkl
  random_mirror: False
  normalization: True
  debug: False

model_args:
  num_class: 226  # autsl
  num_point: 27
  num_person: 1
  graph: graph.sign_27_cvpr.Graph
  A_hands: graph.sign_27_A_hands.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001

# training
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
nesterov: True
